"""
Package contains the API functionality for benwa.online
A JSONAPI is generated by flask-restless based on the models defined in models.py
processors.py contains pre and post-processors for all calls to the api
"""
import os
from flask import Blueprint, request

from benwaonlineapi.api import processors
from benwaonlineapi.database import db
from benwaonlineapi import models

manager = Api(Blueprint('api', __name__, url_prefix='/api'))
